hack: use the full name of module `onnx.checker`
For unknown reasons, Pylint v2.15.0 raises the following exception with `from
onnx import checker`, which had no issues with the previous versions of Pylint.

```
Exception on node <ImportFrom l.2 at 0x7f935cfde3a0> in file '.../furiosa-sdk-private/python/furiosa-quantizer/furiosa/quantizer/frontend/onnx/utils/check_model.py'
Traceback (most recent call last):
  File ".../lib/python3.9/site-packages/astroid/manager.py", line 249, in file_from_module_name
    value = self._mod_file_cache[(modname, contextfile)]
KeyError: ('onnx.onnx_cpp2py_export.checker', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File ".../lib/python3.9/site-packages/pylint/checkers/variables.py", line 1727, in visit_importfrom
    self._check_module_attrs(node, module, name.split("."))
  File ".../lib/python3.9/site-packages/pylint/checkers/variables.py", line 2652, in _check_module_attrs
    module = next(module.getattr(name)[0].infer())
  File ".../lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 408, in getattr
    result = [self.import_module(name, relative_only=True)]
  File ".../lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 521, in import_module
    return AstroidManager().ast_from_module_name(absmodname)
  File ".../lib/python3.9/site-packages/astroid/manager.py", line 208, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File ".../lib/python3.9/site-packages/astroid/manager.py", line 117, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File ".../lib/python3.9/site-packages/astroid/builder.py", line 135, in file_build
    return self._post_build(module, builder, encoding)
  File ".../lib/python3.9/site-packages/astroid/builder.py", line 157, in _post_build
    self.delayed_assattr(delayed)
  File ".../lib/python3.9/site-packages/astroid/builder.py", line 227, in delayed_assattr
    for inferred in node.expr.infer():
  File ".../lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    yield from self._infer(context=context, **kwargs)
  File ".../lib/python3.9/site-packages/astroid/decorators.py", line 139, in raise_if_nothing_inferred
    yield next(generator)
  File ".../lib/python3.9/site-packages/astroid/decorators.py", line 108, in wrapped
    for res in _func(node, context, **kwargs):
  File ".../lib/python3.9/site-packages/astroid/bases.py", line 165, in _infer_stmts
    for inf in stmt.infer(context=context):  # type: ignore[union-attr]
  File ".../lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 182, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File ".../lib/python3.9/site-packages/astroid/decorators.py", line 139, in raise_if_nothing_inferred
    yield next(generator)
  File ".../lib/python3.9/site-packages/astroid/decorators.py", line 108, in wrapped
    for res in _func(node, context, **kwargs):
  File ".../lib/python3.9/site-packages/astroid/bases.py", line 165, in _infer_stmts
    for inf in stmt.infer(context=context):  # type: ignore[union-attr]
  File ".../lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 182, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File ".../lib/python3.9/site-packages/astroid/decorators.py", line 139, in raise_if_nothing_inferred
    yield next(generator)
  File ".../lib/python3.9/site-packages/astroid/decorators.py", line 108, in wrapped
    for res in _func(node, context, **kwargs):
  File ".../lib/python3.9/site-packages/astroid/inference.py", line 255, in infer_call
    for callee in self.func.infer(context):
  File ".../lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 182, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File ".../lib/python3.9/site-packages/astroid/decorators.py", line 139, in raise_if_nothing_inferred
    yield next(generator)
  File ".../lib/python3.9/site-packages/astroid/decorators.py", line 108, in wrapped
    for res in _func(node, context, **kwargs):
  File ".../lib/python3.9/site-packages/astroid/inference.py", line 343, in infer_attribute
    for owner in self.expr.infer(context):
  File ".../lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 182, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File ".../lib/python3.9/site-packages/astroid/decorators.py", line 139, in raise_if_nothing_inferred
    yield next(generator)
  File ".../lib/python3.9/site-packages/astroid/decorators.py", line 108, in wrapped
    for res in _func(node, context, **kwargs):
  File ".../lib/python3.9/site-packages/astroid/bases.py", line 165, in _infer_stmts
    for inf in stmt.infer(context=context):  # type: ignore[union-attr]
  File ".../lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 182, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File ".../lib/python3.9/site-packages/astroid/decorators.py", line 139, in raise_if_nothing_inferred
    yield next(generator)
  File ".../lib/python3.9/site-packages/astroid/decorators.py", line 108, in wrapped
    for res in _func(node, context, **kwargs):
  File ".../lib/python3.9/site-packages/astroid/inference.py", line 289, in infer_import
    yield self.do_import_module(self.real_name(name))
  File ".../lib/python3.9/site-packages/astroid/nodes/_base_nodes.py", line 148, in do_import_module
    return mymodule.import_module(
  File ".../lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 521, in import_module
    return AstroidManager().ast_from_module_name(absmodname)
  File ".../lib/python3.9/site-packages/astroid/manager.py", line 160, in ast_from_module_name
    found_spec = self.file_from_module_name(modname, context_file)
  File ".../lib/python3.9/site-packages/astroid/manager.py", line 252, in file_from_module_name
    value = file_info_from_modpath(
  File ".../lib/python3.9/site-packages/astroid/modutils.py", line 384, in file_info_from_modpath
    return _spec_from_modpath(modpath, path, context)
  File ".../lib/python3.9/site-packages/astroid/modutils.py", line 596, in _spec_from_modpath
    found_spec = spec.find_spec(modpath, path)
  File ".../lib/python3.9/site-packages/astroid/interpreter/_import/spec.py", line 392, in find_spec
    finder, spec = _find_spec_with_path(
  File ".../lib/python3.9/site-packages/astroid/interpreter/_import/spec.py", line 354, in _find_spec_with_path
    spec = finder_instance.find_module(
  File ".../lib/python3.9/site-packages/astroid/interpreter/_import/spec.py", line 204, in find_module
    submodule_path = sys.modules[modname].__path__
AttributeError: module 'onnx.onnx_cpp2py_export.checker' has no attribute '__path__'
************* Module quantizer.frontend.onnx.utils.check_model
furiosa/quantizer/frontend/onnx/utils/check_model.py:1:0: F0002: furiosa/quantizer/frontend/onnx/utils/check_model.py: Fatal error while checking 'furiosa/quantizer/frontend/onnx/utils/check_model.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/root/.cache/pylint/pylint-crash-2022-08-28-10-39-22.txt'. (astroid-error)
```